{% set version = "0.15.0" %}

package:
  name: check
  version: {{ version }}

source:
  url: https://github.com/libcheck/check/releases/download/{{ version }}/check-{{ version }}.tar.gz
  sha256: aea2e3c68fa6e1e92378e744b1c0db350ccda4b6bd0d19530d0ae185b3d1ac60

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - {{ compiler('c') }}
  host:
    - texinfo

test:
  commands:
    - checkmk --version

about:
  home: http://libcheck.github.io/check/
  license: LGPL-2.1
  license_file: COPYING.LESSER
  summary: Unit testing framework for C

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
