{% set version = "0.12.0" %}

package:
  name: check
  version: {{ version }}

source:
  fn: check-{{ version }}.tar.gz
  url: https://github.com/libcheck/check/releases/download/{{ version }}/check-{{ version }}.tar.gz
  sha256: 464201098bee00e90f5c4bdfa94a5d3ead8d641f9025b560a27755a83b824234

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - texinfo

test:
  commands:
    - checkmk --version
    #- conda inspect linkages -p $PREFIX check  # [not win]
    #- conda inspect objects -p $PREFIX check  # [osx]

about:
  home: http://libcheck.github.io/check/
  license: LGPL-2.1
  summary: 'Unit testing framework for C.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
