{% set version = "0.13.0" %}

package:
  name: check
  version: {{ version }}

source:
  url: https://github.com/libcheck/check/releases/download/{{ version }}/check-{{ version }}.tar.gz
  sha256: c4336b31447acc7e3266854f73ec188cdb15554d0edd44739631da174a569909

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - {{ compiler('c') }}
  host:
    - texinfo

test:
  commands:
    - checkmk --version

about:
  home: http://libcheck.github.io/check/
  license: LGPL-2.1
  license_file: COPYING.LESSER
  summary: 'Unit testing framework for C'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
