travis:
  secure:
    BINSTAR_TOKEN: eKzQWZDt3DgDsCKITH3d+rhtofMGz9jBmeVden9AX3FU+ZhDCerXvoaLw0+SpEV98DGK3GSdRGfP6SUFedn7jjZOmKS/16ThCG0TFql052a730DmCxYUNmlL6aIRzT+PSNgbBqdqjC0xykQx2RDnemtO4fQ0FjUoWCLoE8bl9sG9HEnoGMFLNBeNpuqxRAHhokq12QLnCtdLGy0t9CuZJG6MpQ5SpCwzys3+sozB+NkDX3lCns+oer6M/ca1vLDk0inA60J4f8UvOjmvWtSv29IldHaxjHub5uCYY5lyL90Vuc6UCX8JdHpSUxR+tuBJwHmsInhm9HuNnqZbt5rBomd5PeHY0vxrW/tT5CRfKdVtJ3+6ApP0dzaKl/IRiUq1lxTN8aZouBfBUIXzWQeKQxwHakduVSEk7XM/TnfcMjUVCNkS7/aN5Ao+AWtudv7Dy7+8TGPp9agIRSt34ni9kv/TiE5FPLy8RXPou/NTj3+JSIOSLd2P9C0j/58dNrDYOc/TglBMrC/63EbazesFIpIBongdEvcaSlAOVJDt28JoHdTwK0rtsadBM/v9ugYpodhRfBfTfpBYlXLlfBOmXfhIqdaR8zvmbdV7HPOQjQaqL0J16hJRG8Y04tt9vacm7it0Kt/6QoUxV95irKoLvzkjC+zYaVDMHXMH7HRKwqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
